/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 133
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_namespace = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_instance = 5,
  anon_sym_EQ = 6,
  anon_sym_SEMI = 7,
  anon_sym_in = 8,
  anon_sym_tags = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_COLON_COLON = 13,
  anon_sym_COLON = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  sym_true = 17,
  sym_false = 18,
  sym_integer = 19,
  anon_sym_DQUOTE = 20,
  anon_sym_DQUOTE2 = 21,
  sym_string_content = 22,
  sym_escape_sequence = 23,
  sym_comment = 24,
  sym_entities = 25,
  sym_namespace = 26,
  sym_instance = 27,
  sym_instance_parents = 28,
  sym_instance_tags = 29,
  sym_entity_list = 30,
  sym_entity_reference = 31,
  sym_record = 32,
  sym_record_entry = 33,
  sym__value = 34,
  sym_set = 35,
  sym_extension_call = 36,
  sym_name = 37,
  sym_string = 38,
  aux_sym_entities_repeat1 = 39,
  aux_sym_namespace_repeat1 = 40,
  aux_sym_entity_list_repeat1 = 41,
  aux_sym_entity_reference_repeat1 = 42,
  aux_sym_record_repeat1 = 43,
  aux_sym_set_repeat1 = 44,
  aux_sym_string_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_namespace] = "namespace",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_instance] = "instance",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_in] = "in",
  [anon_sym_tags] = "tags",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [sym_entities] = "entities",
  [sym_namespace] = "namespace",
  [sym_instance] = "instance",
  [sym_instance_parents] = "instance_parents",
  [sym_instance_tags] = "instance_tags",
  [sym_entity_list] = "entity_list",
  [sym_entity_reference] = "entity_reference",
  [sym_record] = "record",
  [sym_record_entry] = "record_entry",
  [sym__value] = "_value",
  [sym_set] = "set",
  [sym_extension_call] = "extension_call",
  [sym_name] = "name",
  [sym_string] = "string",
  [aux_sym_entities_repeat1] = "entities_repeat1",
  [aux_sym_namespace_repeat1] = "namespace_repeat1",
  [aux_sym_entity_list_repeat1] = "entity_list_repeat1",
  [aux_sym_entity_reference_repeat1] = "entity_reference_repeat1",
  [aux_sym_record_repeat1] = "record_repeat1",
  [aux_sym_set_repeat1] = "set_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_instance] = anon_sym_instance,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_tags] = anon_sym_tags,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [sym_entities] = sym_entities,
  [sym_namespace] = sym_namespace,
  [sym_instance] = sym_instance,
  [sym_instance_parents] = sym_instance_parents,
  [sym_instance_tags] = sym_instance_tags,
  [sym_entity_list] = sym_entity_list,
  [sym_entity_reference] = sym_entity_reference,
  [sym_record] = sym_record,
  [sym_record_entry] = sym_record_entry,
  [sym__value] = sym__value,
  [sym_set] = sym_set,
  [sym_extension_call] = sym_extension_call,
  [sym_name] = sym_name,
  [sym_string] = sym_string,
  [aux_sym_entities_repeat1] = aux_sym_entities_repeat1,
  [aux_sym_namespace_repeat1] = aux_sym_namespace_repeat1,
  [aux_sym_entity_list_repeat1] = aux_sym_entity_list_repeat1,
  [aux_sym_entity_reference_repeat1] = aux_sym_entity_reference_repeat1,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
  [aux_sym_set_repeat1] = aux_sym_set_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_instance] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tags] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_entities] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_instance] = {
    .visible = true,
    .named = true,
  },
  [sym_instance_parents] = {
    .visible = true,
    .named = true,
  },
  [sym_instance_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_list] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_record_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_call] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_entities_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_namespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 11,
  [18] = 12,
  [19] = 15,
  [20] = 11,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 11,
  [26] = 12,
  [27] = 15,
  [28] = 28,
  [29] = 29,
  [30] = 12,
  [31] = 31,
  [32] = 12,
  [33] = 15,
  [34] = 11,
  [35] = 15,
  [36] = 36,
  [37] = 37,
  [38] = 12,
  [39] = 11,
  [40] = 15,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 84,
  [90] = 90,
  [91] = 66,
  [92] = 92,
  [93] = 84,
  [94] = 66,
  [95] = 84,
  [96] = 66,
  [97] = 84,
  [98] = 66,
  [99] = 90,
  [100] = 72,
  [101] = 79,
  [102] = 90,
  [103] = 72,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 111,
  [114] = 114,
  [115] = 111,
  [116] = 116,
  [117] = 116,
  [118] = 116,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 51,
        '(', 46,
        ')', 47,
        ',', 38,
        '/', 8,
        ':', 44,
        ';', 29,
        '=', 27,
        '[', 37,
        '\\', 14,
        ']', 40,
        'i', 68,
        't', 66,
        '{', 23,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead == ']') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '"', 51,
        '/', 59,
        ';', 30,
        '=', 28,
        '\\', 14,
        'i', 62,
        't', 60,
        '{', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '{') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        ')', 47,
        ',', 38,
        '/', 8,
        ':', 43,
        ';', 29,
        '=', 27,
        ']', 40,
        'i', 12,
        't', 10,
        '{', 23,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(71);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(19);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 15:
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == '}') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 20:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 50,
        '(', 46,
        ')', 47,
        ',', 38,
        '/', 8,
        ':', 44,
        ';', 29,
        '=', 27,
        '[', 37,
        ']', 40,
        'i', 68,
        't', 66,
        '{', 23,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 50,
        '(', 46,
        ')', 47,
        ',', 38,
        '/', 8,
        ':', 9,
        '[', 37,
        ']', 40,
        '{', 23,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_tags);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_tags);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_tags);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(71);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '/') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == ']') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(64);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == ':') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(62);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '{') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '{') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 'g') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 'n') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 's') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(71);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_instance);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 21},
  [8] = {.lex_state = 21},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 21},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 21},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 21},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 21},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 21},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 21},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 21},
  [52] = {.lex_state = 21},
  [53] = {.lex_state = 21},
  [54] = {.lex_state = 21},
  [55] = {.lex_state = 21},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 21},
  [59] = {.lex_state = 21},
  [60] = {.lex_state = 21},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 21},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 21},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 21},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 21},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 21},
  [73] = {.lex_state = 21},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 21},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 21},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 21},
  [84] = {.lex_state = 21},
  [85] = {.lex_state = 21},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 7},
  [88] = {.lex_state = 21},
  [89] = {.lex_state = 21},
  [90] = {.lex_state = 21},
  [91] = {.lex_state = 21},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 21},
  [94] = {.lex_state = 21},
  [95] = {.lex_state = 21},
  [96] = {.lex_state = 21},
  [97] = {.lex_state = 21},
  [98] = {.lex_state = 21},
  [99] = {.lex_state = 21},
  [100] = {.lex_state = 21},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 21},
  [103] = {.lex_state = 21},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 21},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 21},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 21},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 21},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 21},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 21},
  [116] = {.lex_state = 21},
  [117] = {.lex_state = 21},
  [118] = {.lex_state = 21},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 7},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 21},
  [132] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_instance] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_tags] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_entities] = STATE(123),
    [sym_namespace] = STATE(31),
    [sym_instance] = STATE(31),
    [aux_sym_entities_repeat1] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_namespace] = ACTIONS(7),
    [anon_sym_instance] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_COMMA,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(120), 1,
      sym_name,
    ACTIONS(21), 2,
      sym_true,
      sym_false,
    STATE(71), 6,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym_string,
  [40] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 1,
      sym_integer,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    STATE(120), 1,
      sym_name,
    ACTIONS(31), 2,
      sym_true,
      sym_false,
    STATE(77), 6,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym_string,
  [77] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(41), 1,
      sym_integer,
    STATE(120), 1,
      sym_name,
    ACTIONS(39), 2,
      sym_true,
      sym_false,
    STATE(78), 6,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym_string,
  [114] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      sym_integer,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    STATE(120), 1,
      sym_name,
    ACTIONS(39), 2,
      sym_true,
      sym_false,
    STATE(78), 6,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym_string,
  [151] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(49), 1,
      sym_integer,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    STATE(120), 1,
      sym_name,
    ACTIONS(47), 2,
      sym_true,
      sym_false,
    STATE(106), 6,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym_string,
  [185] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      sym_integer,
    STATE(120), 1,
      sym_name,
    ACTIONS(39), 2,
      sym_true,
      sym_false,
    STATE(78), 6,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym_string,
  [219] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      sym_integer,
    STATE(120), 1,
      sym_name,
    ACTIONS(39), 2,
      sym_true,
      sym_false,
    STATE(78), 6,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym_string,
  [253] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [285] = 6,
    ACTIONS(59), 1,
      anon_sym_DQUOTE2,
    ACTIONS(61), 1,
      sym_string_content,
    ACTIONS(63), 1,
      sym_escape_sequence,
    ACTIONS(65), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_string_repeat1,
    ACTIONS(57), 5,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
  [308] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_DQUOTE2,
    ACTIONS(71), 1,
      sym_string_content,
    ACTIONS(73), 1,
      sym_escape_sequence,
    STATE(15), 1,
      aux_sym_string_repeat1,
    ACTIONS(67), 5,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
  [331] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [346] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [361] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DQUOTE2,
    ACTIONS(83), 1,
      sym_string_content,
    ACTIONS(86), 1,
      sym_escape_sequence,
    STATE(15), 1,
      aux_sym_string_repeat1,
    ACTIONS(79), 5,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
  [384] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(91), 1,
      anon_sym_SEMI,
    ACTIONS(93), 1,
      anon_sym_in,
    ACTIONS(95), 1,
      anon_sym_tags,
    STATE(24), 1,
      sym_instance_parents,
    STATE(80), 1,
      sym_record,
    STATE(124), 1,
      sym_instance_tags,
  [412] = 6,
    ACTIONS(59), 1,
      anon_sym_DQUOTE2,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_string_content,
    ACTIONS(99), 1,
      sym_escape_sequence,
    STATE(18), 1,
      aux_sym_string_repeat1,
    ACTIONS(57), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [434] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_DQUOTE2,
    ACTIONS(101), 1,
      sym_string_content,
    ACTIONS(103), 1,
      sym_escape_sequence,
    STATE(19), 1,
      aux_sym_string_repeat1,
    ACTIONS(67), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [456] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DQUOTE2,
    ACTIONS(105), 1,
      sym_string_content,
    ACTIONS(108), 1,
      sym_escape_sequence,
    STATE(19), 1,
      aux_sym_string_repeat1,
    ACTIONS(79), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [478] = 6,
    ACTIONS(59), 1,
      anon_sym_DQUOTE2,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_string_content,
    ACTIONS(113), 1,
      sym_escape_sequence,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(57), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [522] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 1,
      anon_sym_namespace,
    ACTIONS(124), 1,
      anon_sym_instance,
    STATE(23), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [540] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(95), 1,
      anon_sym_tags,
    ACTIONS(127), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_SEMI,
    STATE(70), 1,
      sym_record,
    STATE(128), 1,
      sym_instance_tags,
  [562] = 6,
    ACTIONS(59), 1,
      anon_sym_DQUOTE2,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_string_content,
    ACTIONS(133), 1,
      sym_escape_sequence,
    STATE(26), 1,
      aux_sym_string_repeat1,
    ACTIONS(57), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [582] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_DQUOTE2,
    ACTIONS(135), 1,
      sym_string_content,
    ACTIONS(137), 1,
      sym_escape_sequence,
    STATE(27), 1,
      aux_sym_string_repeat1,
    ACTIONS(67), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [602] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DQUOTE2,
    ACTIONS(139), 1,
      sym_string_content,
    ACTIONS(142), 1,
      sym_escape_sequence,
    STATE(27), 1,
      aux_sym_string_repeat1,
    ACTIONS(79), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [622] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_record_entry,
    STATE(126), 1,
      sym_string,
  [644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [656] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_DQUOTE2,
    ACTIONS(155), 1,
      sym_string_content,
    ACTIONS(157), 1,
      sym_escape_sequence,
    STATE(35), 1,
      aux_sym_string_repeat1,
    ACTIONS(67), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [676] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
    STATE(23), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [694] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_DQUOTE2,
    ACTIONS(161), 1,
      sym_string_content,
    ACTIONS(163), 1,
      sym_escape_sequence,
    STATE(33), 1,
      aux_sym_string_repeat1,
    ACTIONS(67), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [714] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DQUOTE2,
    ACTIONS(165), 1,
      sym_string_content,
    ACTIONS(168), 1,
      sym_escape_sequence,
    STATE(33), 1,
      aux_sym_string_repeat1,
    ACTIONS(79), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [734] = 6,
    ACTIONS(59), 1,
      anon_sym_DQUOTE2,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_string_content,
    ACTIONS(173), 1,
      sym_escape_sequence,
    STATE(30), 1,
      aux_sym_string_repeat1,
    ACTIONS(57), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [754] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DQUOTE2,
    ACTIONS(175), 1,
      sym_string_content,
    ACTIONS(178), 1,
      sym_escape_sequence,
    STATE(35), 1,
      aux_sym_string_repeat1,
    ACTIONS(79), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [774] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [786] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(112), 1,
      sym_record_entry,
    STATE(126), 1,
      sym_string,
  [805] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_COLON,
    ACTIONS(69), 1,
      anon_sym_DQUOTE2,
    ACTIONS(185), 1,
      sym_string_content,
    ACTIONS(187), 1,
      sym_escape_sequence,
    STATE(40), 1,
      aux_sym_string_repeat1,
  [824] = 6,
    ACTIONS(57), 1,
      anon_sym_COLON,
    ACTIONS(59), 1,
      anon_sym_DQUOTE2,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_string_content,
    ACTIONS(191), 1,
      sym_escape_sequence,
    STATE(38), 1,
      aux_sym_string_repeat1,
  [843] = 6,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_COLON,
    ACTIONS(81), 1,
      anon_sym_DQUOTE2,
    ACTIONS(193), 1,
      sym_string_content,
    ACTIONS(196), 1,
      sym_escape_sequence,
    STATE(40), 1,
      aux_sym_string_repeat1,
  [862] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(112), 1,
      sym_record_entry,
    STATE(126), 1,
      sym_string,
  [881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
  [891] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 4,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
  [921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [961] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [971] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
  [981] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    ACTIONS(223), 1,
      anon_sym_instance,
    STATE(52), 2,
      sym_instance,
      aux_sym_namespace_repeat1,
  [995] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_COLON_COLON,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
    ACTIONS(226), 2,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [1009] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(231), 1,
      anon_sym_RBRACE,
    STATE(52), 2,
      sym_instance,
      aux_sym_namespace_repeat1,
  [1023] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 4,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
  [1033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [1043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1053] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 4,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
  [1063] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
    ACTIONS(243), 1,
      anon_sym_LBRACK,
    STATE(50), 2,
      sym_entity_list,
      sym_entity_reference,
  [1077] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    STATE(112), 1,
      sym_record_entry,
    STATE(126), 1,
      sym_string,
  [1093] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [1103] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
    STATE(54), 2,
      sym_instance,
      aux_sym_namespace_repeat1,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1127] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      sym_entity_reference,
  [1143] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1153] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(261), 1,
      anon_sym_DQUOTE,
    STATE(14), 1,
      sym_string,
  [1166] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(104), 1,
      aux_sym_record_repeat1,
  [1179] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(267), 1,
      anon_sym_RBRACK,
    STATE(114), 1,
      sym_entity_reference,
  [1192] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_RBRACK,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_entity_list_repeat1,
  [1205] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_tags,
    ACTIONS(271), 1,
      anon_sym_SEMI,
    STATE(130), 1,
      sym_instance_tags,
  [1218] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_set_repeat1,
  [1231] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COLON_COLON,
    ACTIONS(279), 1,
      anon_sym_LPAREN,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
  [1244] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(281), 1,
      anon_sym_RBRACK,
    STATE(114), 1,
      sym_entity_reference,
  [1257] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
    STATE(74), 1,
      aux_sym_entity_list_repeat1,
  [1270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 3,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_instance,
  [1279] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_set_repeat1,
  [1292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_set_repeat1,
  [1305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_RBRACK,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_set_repeat1,
  [1327] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_tags,
    ACTIONS(129), 1,
      anon_sym_SEMI,
    STATE(128), 1,
      sym_instance_tags,
  [1340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 3,
      anon_sym_LBRACE,
      anon_sym_COLON_COLON,
      anon_sym_LPAREN,
  [1349] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      aux_sym_set_repeat1,
  [1362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 3,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_instance,
  [1371] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      sym_string,
  [1384] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_LBRACE,
    ACTIONS(307), 1,
      anon_sym_COLON_COLON,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
  [1397] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RBRACK,
    STATE(69), 1,
      aux_sym_entity_list_repeat1,
  [1410] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_tags,
    ACTIONS(313), 1,
      anon_sym_SEMI,
    STATE(127), 1,
      sym_instance_tags,
  [1423] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_COLON_COLON,
    ACTIONS(315), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      aux_sym_entity_reference_repeat1,
  [1436] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(261), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      sym_string,
  [1449] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_LPAREN,
    ACTIONS(317), 1,
      anon_sym_COLON_COLON,
    STATE(72), 1,
      aux_sym_entity_reference_repeat1,
  [1462] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    STATE(14), 1,
      sym_string,
  [1475] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym_record_repeat1,
  [1488] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(13), 1,
      sym_string,
  [1501] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(14), 1,
      sym_string,
  [1514] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(13), 1,
      sym_string,
  [1527] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(14), 1,
      sym_string,
  [1540] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(13), 1,
      sym_string,
  [1553] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(14), 1,
      sym_string,
  [1566] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_LPAREN,
    ACTIONS(324), 1,
      anon_sym_COLON_COLON,
    STATE(100), 1,
      aux_sym_entity_reference_repeat1,
  [1579] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_LPAREN,
    ACTIONS(326), 1,
      anon_sym_COLON_COLON,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
  [1592] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    ACTIONS(328), 1,
      anon_sym_COMMA,
    STATE(101), 1,
      aux_sym_set_repeat1,
  [1605] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_LPAREN,
    ACTIONS(331), 1,
      anon_sym_COLON_COLON,
    STATE(103), 1,
      aux_sym_entity_reference_repeat1,
  [1618] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_LPAREN,
    ACTIONS(333), 1,
      anon_sym_COLON_COLON,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
  [1631] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(335), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym_record_repeat1,
  [1644] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_identifier,
    STATE(16), 1,
      sym_entity_reference,
  [1654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1662] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_identifier,
    STATE(129), 1,
      sym_name,
  [1672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(122), 1,
      sym_record,
  [1682] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(114), 1,
      sym_entity_reference,
  [1692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(87), 1,
      sym_record,
  [1702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_COLON_COLON,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
  [1712] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_COLON_COLON,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_COLON_COLON,
    STATE(53), 1,
      aux_sym_entity_reference_repeat1,
  [1748] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_COLON_COLON,
    STATE(115), 1,
      aux_sym_entity_reference_repeat1,
  [1758] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_COLON_COLON,
    STATE(111), 1,
      aux_sym_entity_reference_repeat1,
  [1768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_COLON_COLON,
    STATE(113), 1,
      aux_sym_entity_reference_repeat1,
  [1778] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(70), 1,
      sym_record,
  [1788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_LPAREN,
  [1795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
  [1802] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_SEMI,
  [1809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      ts_builtin_sym_end,
  [1816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_SEMI,
  [1823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
  [1830] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_COLON,
  [1837] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_SEMI,
  [1844] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_SEMI,
  [1851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_LBRACE,
  [1858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_SEMI,
  [1865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identifier,
  [1872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 77,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 151,
  [SMALL_STATE(7)] = 185,
  [SMALL_STATE(8)] = 219,
  [SMALL_STATE(9)] = 253,
  [SMALL_STATE(10)] = 269,
  [SMALL_STATE(11)] = 285,
  [SMALL_STATE(12)] = 308,
  [SMALL_STATE(13)] = 331,
  [SMALL_STATE(14)] = 346,
  [SMALL_STATE(15)] = 361,
  [SMALL_STATE(16)] = 384,
  [SMALL_STATE(17)] = 412,
  [SMALL_STATE(18)] = 434,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 478,
  [SMALL_STATE(21)] = 498,
  [SMALL_STATE(22)] = 510,
  [SMALL_STATE(23)] = 522,
  [SMALL_STATE(24)] = 540,
  [SMALL_STATE(25)] = 562,
  [SMALL_STATE(26)] = 582,
  [SMALL_STATE(27)] = 602,
  [SMALL_STATE(28)] = 622,
  [SMALL_STATE(29)] = 644,
  [SMALL_STATE(30)] = 656,
  [SMALL_STATE(31)] = 676,
  [SMALL_STATE(32)] = 694,
  [SMALL_STATE(33)] = 714,
  [SMALL_STATE(34)] = 734,
  [SMALL_STATE(35)] = 754,
  [SMALL_STATE(36)] = 774,
  [SMALL_STATE(37)] = 786,
  [SMALL_STATE(38)] = 805,
  [SMALL_STATE(39)] = 824,
  [SMALL_STATE(40)] = 843,
  [SMALL_STATE(41)] = 862,
  [SMALL_STATE(42)] = 881,
  [SMALL_STATE(43)] = 891,
  [SMALL_STATE(44)] = 901,
  [SMALL_STATE(45)] = 911,
  [SMALL_STATE(46)] = 921,
  [SMALL_STATE(47)] = 931,
  [SMALL_STATE(48)] = 941,
  [SMALL_STATE(49)] = 951,
  [SMALL_STATE(50)] = 961,
  [SMALL_STATE(51)] = 971,
  [SMALL_STATE(52)] = 981,
  [SMALL_STATE(53)] = 995,
  [SMALL_STATE(54)] = 1009,
  [SMALL_STATE(55)] = 1023,
  [SMALL_STATE(56)] = 1033,
  [SMALL_STATE(57)] = 1043,
  [SMALL_STATE(58)] = 1053,
  [SMALL_STATE(59)] = 1063,
  [SMALL_STATE(60)] = 1077,
  [SMALL_STATE(61)] = 1093,
  [SMALL_STATE(62)] = 1103,
  [SMALL_STATE(63)] = 1117,
  [SMALL_STATE(64)] = 1127,
  [SMALL_STATE(65)] = 1143,
  [SMALL_STATE(66)] = 1153,
  [SMALL_STATE(67)] = 1166,
  [SMALL_STATE(68)] = 1179,
  [SMALL_STATE(69)] = 1192,
  [SMALL_STATE(70)] = 1205,
  [SMALL_STATE(71)] = 1218,
  [SMALL_STATE(72)] = 1231,
  [SMALL_STATE(73)] = 1244,
  [SMALL_STATE(74)] = 1257,
  [SMALL_STATE(75)] = 1270,
  [SMALL_STATE(76)] = 1279,
  [SMALL_STATE(77)] = 1292,
  [SMALL_STATE(78)] = 1305,
  [SMALL_STATE(79)] = 1314,
  [SMALL_STATE(80)] = 1327,
  [SMALL_STATE(81)] = 1340,
  [SMALL_STATE(82)] = 1349,
  [SMALL_STATE(83)] = 1362,
  [SMALL_STATE(84)] = 1371,
  [SMALL_STATE(85)] = 1384,
  [SMALL_STATE(86)] = 1397,
  [SMALL_STATE(87)] = 1410,
  [SMALL_STATE(88)] = 1423,
  [SMALL_STATE(89)] = 1436,
  [SMALL_STATE(90)] = 1449,
  [SMALL_STATE(91)] = 1462,
  [SMALL_STATE(92)] = 1475,
  [SMALL_STATE(93)] = 1488,
  [SMALL_STATE(94)] = 1501,
  [SMALL_STATE(95)] = 1514,
  [SMALL_STATE(96)] = 1527,
  [SMALL_STATE(97)] = 1540,
  [SMALL_STATE(98)] = 1553,
  [SMALL_STATE(99)] = 1566,
  [SMALL_STATE(100)] = 1579,
  [SMALL_STATE(101)] = 1592,
  [SMALL_STATE(102)] = 1605,
  [SMALL_STATE(103)] = 1618,
  [SMALL_STATE(104)] = 1631,
  [SMALL_STATE(105)] = 1644,
  [SMALL_STATE(106)] = 1654,
  [SMALL_STATE(107)] = 1662,
  [SMALL_STATE(108)] = 1672,
  [SMALL_STATE(109)] = 1682,
  [SMALL_STATE(110)] = 1692,
  [SMALL_STATE(111)] = 1702,
  [SMALL_STATE(112)] = 1712,
  [SMALL_STATE(113)] = 1720,
  [SMALL_STATE(114)] = 1730,
  [SMALL_STATE(115)] = 1738,
  [SMALL_STATE(116)] = 1748,
  [SMALL_STATE(117)] = 1758,
  [SMALL_STATE(118)] = 1768,
  [SMALL_STATE(119)] = 1778,
  [SMALL_STATE(120)] = 1788,
  [SMALL_STATE(121)] = 1795,
  [SMALL_STATE(122)] = 1802,
  [SMALL_STATE(123)] = 1809,
  [SMALL_STATE(124)] = 1816,
  [SMALL_STATE(125)] = 1823,
  [SMALL_STATE(126)] = 1830,
  [SMALL_STATE(127)] = 1837,
  [SMALL_STATE(128)] = 1844,
  [SMALL_STATE(129)] = 1851,
  [SMALL_STATE(130)] = 1858,
  [SMALL_STATE(131)] = 1865,
  [SMALL_STATE(132)] = 1872,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entities, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_reference, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_reference, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entities_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entities_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entities_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entities, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 7, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 5, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 4, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 5, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_call, 4, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 5, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_call, 5, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance_parents, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_reference_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entity_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 6, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 4, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_call, 3, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 2, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entity_list_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_list_repeat1, 2, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 5, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 0),
  [298] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 4, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [321] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [328] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_entry, 3, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance_tags, 2, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cedarentities(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cedarentities",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
