/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 156
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_namespace = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_instance = 5,
  anon_sym_EQ = 6,
  anon_sym_SEMI = 7,
  anon_sym_in = 8,
  anon_sym_tags = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_COLON_COLON = 13,
  anon_sym_COLON = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  sym_true = 17,
  sym_false = 18,
  sym_integer = 19,
  sym_decimal = 20,
  anon_sym_DASH = 21,
  anon_sym_DQUOTE = 22,
  anon_sym_DQUOTE2 = 23,
  sym_string_content = 24,
  sym_escape_sequence = 25,
  anon_sym_AT = 26,
  sym_comment = 27,
  sym_entities = 28,
  sym_namespace = 29,
  sym_instance = 30,
  sym_instance_parents = 31,
  sym_instance_tags = 32,
  sym_entity_list = 33,
  sym_entity_reference = 34,
  sym_record = 35,
  sym_record_entry = 36,
  sym__value = 37,
  sym_set = 38,
  sym_extension_call = 39,
  sym__literal = 40,
  sym_name = 41,
  sym__number = 42,
  sym_string = 43,
  sym_annotation = 44,
  aux_sym_entities_repeat1 = 45,
  aux_sym_namespace_repeat1 = 46,
  aux_sym_entity_list_repeat1 = 47,
  aux_sym_entity_reference_repeat1 = 48,
  aux_sym_record_repeat1 = 49,
  aux_sym_set_repeat1 = 50,
  aux_sym_string_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_namespace] = "namespace",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_instance] = "instance",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_in] = "in",
  [anon_sym_tags] = "tags",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_integer] = "integer",
  [sym_decimal] = "decimal",
  [anon_sym_DASH] = "-",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_AT] = "@",
  [sym_comment] = "comment",
  [sym_entities] = "entities",
  [sym_namespace] = "namespace",
  [sym_instance] = "instance",
  [sym_instance_parents] = "instance_parents",
  [sym_instance_tags] = "instance_tags",
  [sym_entity_list] = "entity_list",
  [sym_entity_reference] = "entity_reference",
  [sym_record] = "record",
  [sym_record_entry] = "record_entry",
  [sym__value] = "_value",
  [sym_set] = "set",
  [sym_extension_call] = "extension_call",
  [sym__literal] = "_literal",
  [sym_name] = "name",
  [sym__number] = "_number",
  [sym_string] = "string",
  [sym_annotation] = "annotation",
  [aux_sym_entities_repeat1] = "entities_repeat1",
  [aux_sym_namespace_repeat1] = "namespace_repeat1",
  [aux_sym_entity_list_repeat1] = "entity_list_repeat1",
  [aux_sym_entity_reference_repeat1] = "entity_reference_repeat1",
  [aux_sym_record_repeat1] = "record_repeat1",
  [aux_sym_set_repeat1] = "set_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_instance] = anon_sym_instance,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_tags] = anon_sym_tags,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_integer] = sym_integer,
  [sym_decimal] = sym_decimal,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_AT] = anon_sym_AT,
  [sym_comment] = sym_comment,
  [sym_entities] = sym_entities,
  [sym_namespace] = sym_namespace,
  [sym_instance] = sym_instance,
  [sym_instance_parents] = sym_instance_parents,
  [sym_instance_tags] = sym_instance_tags,
  [sym_entity_list] = sym_entity_list,
  [sym_entity_reference] = sym_entity_reference,
  [sym_record] = sym_record,
  [sym_record_entry] = sym_record_entry,
  [sym__value] = sym__value,
  [sym_set] = sym_set,
  [sym_extension_call] = sym_extension_call,
  [sym__literal] = sym__literal,
  [sym_name] = sym_name,
  [sym__number] = sym__number,
  [sym_string] = sym_string,
  [sym_annotation] = sym_annotation,
  [aux_sym_entities_repeat1] = aux_sym_entities_repeat1,
  [aux_sym_namespace_repeat1] = aux_sym_namespace_repeat1,
  [aux_sym_entity_list_repeat1] = aux_sym_entity_list_repeat1,
  [aux_sym_entity_reference_repeat1] = aux_sym_entity_reference_repeat1,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
  [aux_sym_set_repeat1] = aux_sym_set_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_instance] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tags] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_entities] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_instance] = {
    .visible = true,
    .named = true,
  },
  [sym_instance_parents] = {
    .visible = true,
    .named = true,
  },
  [sym_instance_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_list] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_record_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_call] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_entities_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_namespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 15,
  [25] = 13,
  [26] = 20,
  [27] = 13,
  [28] = 20,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 15,
  [34] = 13,
  [35] = 20,
  [36] = 36,
  [37] = 15,
  [38] = 13,
  [39] = 20,
  [40] = 15,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 15,
  [50] = 13,
  [51] = 20,
  [52] = 15,
  [53] = 13,
  [54] = 20,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 87,
  [106] = 106,
  [107] = 106,
  [108] = 87,
  [109] = 106,
  [110] = 87,
  [111] = 106,
  [112] = 87,
  [113] = 103,
  [114] = 88,
  [115] = 94,
  [116] = 103,
  [117] = 88,
  [118] = 106,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 120,
  [130] = 130,
  [131] = 131,
  [132] = 130,
  [133] = 133,
  [134] = 130,
  [135] = 135,
  [136] = 120,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 55,
        '(', 48,
        ')', 49,
        ',', 40,
        '-', 53,
        '/', 9,
        ':', 46,
        ';', 31,
        '=', 29,
        '@', 71,
        '[', 39,
        '\\', 15,
        ']', 42,
        'i', 74,
        't', 72,
        '{', 25,
        '}', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == ']') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == ':') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '"', 55,
        '/', 64,
        ';', 32,
        '=', 30,
        '\\', 15,
        'i', 67,
        't', 65,
        '{', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 't') ADVANCE(65);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        ')', 49,
        ',', 40,
        '/', 9,
        ':', 45,
        ';', 31,
        '=', 29,
        ']', 42,
        'i', 13,
        't', 11,
        '{', 25,
        '}', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(77);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(44);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'g') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(21);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 16:
      if (lookahead == '{') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == '}') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 54,
        '(', 48,
        ')', 49,
        ',', 40,
        '-', 53,
        '/', 9,
        ':', 46,
        ';', 31,
        '=', 29,
        '@', 71,
        '[', 39,
        ']', 42,
        'i', 74,
        't', 72,
        '{', 25,
        '}', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 54,
        '(', 48,
        ')', 49,
        ',', 40,
        '-', 53,
        '/', 9,
        ':', 10,
        '@', 71,
        '[', 39,
        ']', 42,
        '{', 25,
        '}', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_tags);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_tags);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_tags);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(44);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(77);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == '/') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == ']') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(69);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == ':') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(67);
      if (lookahead == 't') ADVANCE(65);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == 't') ADVANCE(65);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 'g') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 'n') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == 's') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_instance);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 23},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 23},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 23},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 23},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 23},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 23},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 23},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 23},
  [44] = {.lex_state = 23},
  [45] = {.lex_state = 23},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 23},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 23},
  [56] = {.lex_state = 23},
  [57] = {.lex_state = 23},
  [58] = {.lex_state = 23},
  [59] = {.lex_state = 23},
  [60] = {.lex_state = 23},
  [61] = {.lex_state = 23},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 23},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 23},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 23},
  [72] = {.lex_state = 23},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 8},
  [77] = {.lex_state = 8},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 23},
  [81] = {.lex_state = 23},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 8},
  [85] = {.lex_state = 8},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 23},
  [88] = {.lex_state = 23},
  [89] = {.lex_state = 23},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 8},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 23},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 8},
  [102] = {.lex_state = 23},
  [103] = {.lex_state = 23},
  [104] = {.lex_state = 23},
  [105] = {.lex_state = 23},
  [106] = {.lex_state = 23},
  [107] = {.lex_state = 23},
  [108] = {.lex_state = 23},
  [109] = {.lex_state = 23},
  [110] = {.lex_state = 23},
  [111] = {.lex_state = 23},
  [112] = {.lex_state = 23},
  [113] = {.lex_state = 23},
  [114] = {.lex_state = 23},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 23},
  [117] = {.lex_state = 23},
  [118] = {.lex_state = 23},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 23},
  [121] = {.lex_state = 23},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 23},
  [124] = {.lex_state = 23},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 23},
  [130] = {.lex_state = 23},
  [131] = {.lex_state = 23},
  [132] = {.lex_state = 23},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 23},
  [135] = {.lex_state = 23},
  [136] = {.lex_state = 23},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 23},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 23},
  [143] = {.lex_state = 23},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 8},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_instance] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_tags] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_decimal] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_entities] = STATE(146),
    [sym_namespace] = STATE(19),
    [sym_instance] = STATE(19),
    [sym_annotation] = STATE(43),
    [aux_sym_entities_repeat1] = STATE(19),
    [aux_sym_namespace_repeat1] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_namespace] = ACTIONS(7),
    [anon_sym_instance] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_COMMA,
    ACTIONS(21), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      sym_decimal,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    STATE(148), 1,
      sym_name,
    ACTIONS(23), 3,
      sym_true,
      sym_false,
      sym_integer,
    STATE(86), 8,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym__literal,
      sym__number,
      sym_string,
  [46] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 1,
      sym_decimal,
    STATE(148), 1,
      sym_name,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_integer,
    STATE(93), 8,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym__literal,
      sym__number,
      sym_string,
  [89] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    ACTIONS(43), 1,
      sym_decimal,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    STATE(148), 1,
      sym_name,
    ACTIONS(41), 3,
      sym_true,
      sym_false,
      sym_integer,
    STATE(92), 8,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym__literal,
      sym__number,
      sym_string,
  [132] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      sym_decimal,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    STATE(148), 1,
      sym_name,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_integer,
    STATE(93), 8,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym__literal,
      sym__number,
      sym_string,
  [175] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(53), 1,
      sym_decimal,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    STATE(148), 1,
      sym_name,
    ACTIONS(51), 3,
      sym_true,
      sym_false,
      sym_integer,
    STATE(119), 8,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym__literal,
      sym__number,
      sym_string,
  [215] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(35), 1,
      sym_decimal,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    STATE(148), 1,
      sym_name,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_integer,
    STATE(93), 8,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym__literal,
      sym__number,
      sym_string,
  [255] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      sym_decimal,
    STATE(148), 1,
      sym_name,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_integer,
    STATE(93), 8,
      sym_entity_reference,
      sym_record,
      sym__value,
      sym_set,
      sym_extension_call,
      sym__literal,
      sym__number,
      sym_string,
  [295] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_namespace,
    ACTIONS(62), 1,
      anon_sym_instance,
    ACTIONS(65), 1,
      anon_sym_AT,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
    STATE(9), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [353] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
    STATE(14), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [378] = 6,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(78), 1,
      sym_string_content,
    ACTIONS(80), 1,
      sym_escape_sequence,
    ACTIONS(82), 1,
      sym_comment,
    STATE(20), 1,
      aux_sym_string_repeat1,
    ACTIONS(74), 5,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
  [401] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
    STATE(9), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [426] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE2,
    ACTIONS(90), 1,
      sym_string_content,
    ACTIONS(92), 1,
      sym_escape_sequence,
    STATE(13), 1,
      aux_sym_string_repeat1,
    ACTIONS(86), 5,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
  [449] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [464] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
    STATE(21), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [504] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    STATE(43), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
    STATE(9), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [529] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DQUOTE2,
    ACTIONS(104), 1,
      sym_string_content,
    ACTIONS(107), 1,
      sym_escape_sequence,
    STATE(20), 1,
      aux_sym_string_repeat1,
    ACTIONS(100), 5,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_in,
      anon_sym_tags,
  [552] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_namespace,
    ACTIONS(9), 1,
      anon_sym_instance,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
    STATE(9), 3,
      sym_namespace,
      sym_instance,
      aux_sym_entities_repeat1,
  [577] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(112), 1,
      anon_sym_EQ,
    ACTIONS(114), 1,
      anon_sym_SEMI,
    ACTIONS(116), 1,
      anon_sym_in,
    ACTIONS(118), 1,
      anon_sym_tags,
    STATE(41), 1,
      sym_instance_parents,
    STATE(95), 1,
      sym_record,
    STATE(139), 1,
      sym_instance_tags,
  [605] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_in,
    ACTIONS(118), 1,
      anon_sym_tags,
    ACTIONS(120), 1,
      anon_sym_EQ,
    ACTIONS(122), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      sym_instance_parents,
    STATE(85), 1,
      sym_record,
    STATE(153), 1,
      sym_instance_tags,
  [633] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE2,
    ACTIONS(124), 1,
      sym_string_content,
    ACTIONS(126), 1,
      sym_escape_sequence,
    STATE(25), 1,
      aux_sym_string_repeat1,
    ACTIONS(86), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [655] = 6,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_string_content,
    ACTIONS(130), 1,
      sym_escape_sequence,
    STATE(26), 1,
      aux_sym_string_repeat1,
    ACTIONS(74), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [677] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DQUOTE2,
    ACTIONS(132), 1,
      sym_string_content,
    ACTIONS(135), 1,
      sym_escape_sequence,
    STATE(26), 1,
      aux_sym_string_repeat1,
    ACTIONS(100), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [699] = 6,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_string_content,
    ACTIONS(140), 1,
      sym_escape_sequence,
    STATE(28), 1,
      aux_sym_string_repeat1,
    ACTIONS(74), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [719] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DQUOTE2,
    ACTIONS(142), 1,
      sym_string_content,
    ACTIONS(145), 1,
      sym_escape_sequence,
    STATE(28), 1,
      aux_sym_string_repeat1,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [739] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    STATE(83), 1,
      sym_record_entry,
    STATE(152), 1,
      sym_string,
  [761] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [773] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [785] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [797] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE2,
    ACTIONS(162), 1,
      sym_string_content,
    ACTIONS(164), 1,
      sym_escape_sequence,
    STATE(34), 1,
      aux_sym_string_repeat1,
    ACTIONS(86), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [817] = 6,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_string_content,
    ACTIONS(168), 1,
      sym_escape_sequence,
    STATE(35), 1,
      aux_sym_string_repeat1,
    ACTIONS(74), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [837] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DQUOTE2,
    ACTIONS(170), 1,
      sym_string_content,
    ACTIONS(173), 1,
      sym_escape_sequence,
    STATE(35), 1,
      aux_sym_string_repeat1,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [857] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_tags,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    STATE(101), 1,
      sym_record,
    STATE(147), 1,
      sym_instance_tags,
  [879] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE2,
    ACTIONS(180), 1,
      sym_string_content,
    ACTIONS(182), 1,
      sym_escape_sequence,
    STATE(38), 1,
      aux_sym_string_repeat1,
    ACTIONS(86), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [899] = 6,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_string_content,
    ACTIONS(186), 1,
      sym_escape_sequence,
    STATE(39), 1,
      aux_sym_string_repeat1,
    ACTIONS(74), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [919] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DQUOTE2,
    ACTIONS(188), 1,
      sym_string_content,
    ACTIONS(191), 1,
      sym_escape_sequence,
    STATE(39), 1,
      aux_sym_string_repeat1,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [939] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE2,
    ACTIONS(194), 1,
      sym_string_content,
    ACTIONS(196), 1,
      sym_escape_sequence,
    STATE(27), 1,
      aux_sym_string_repeat1,
    ACTIONS(86), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [959] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_tags,
    ACTIONS(120), 1,
      anon_sym_EQ,
    ACTIONS(122), 1,
      anon_sym_SEMI,
    STATE(85), 1,
      sym_record,
    STATE(153), 1,
      sym_instance_tags,
  [981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 6,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_tags,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [993] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(200), 1,
      anon_sym_namespace,
    ACTIONS(202), 1,
      anon_sym_instance,
    STATE(55), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
  [1010] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1065] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_COLON,
    ACTIONS(88), 1,
      anon_sym_DQUOTE2,
    ACTIONS(214), 1,
      sym_string_content,
    ACTIONS(216), 1,
      sym_escape_sequence,
    STATE(50), 1,
      aux_sym_string_repeat1,
  [1084] = 6,
    ACTIONS(74), 1,
      anon_sym_COLON,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_string_content,
    ACTIONS(220), 1,
      sym_escape_sequence,
    STATE(51), 1,
      aux_sym_string_repeat1,
  [1103] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_COLON,
    ACTIONS(102), 1,
      anon_sym_DQUOTE2,
    ACTIONS(222), 1,
      sym_string_content,
    ACTIONS(225), 1,
      sym_escape_sequence,
    STATE(51), 1,
      aux_sym_string_repeat1,
  [1122] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    ACTIONS(88), 1,
      anon_sym_DQUOTE2,
    ACTIONS(228), 1,
      sym_string_content,
    ACTIONS(230), 1,
      sym_escape_sequence,
    STATE(53), 1,
      aux_sym_string_repeat1,
  [1141] = 6,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_string_content,
    ACTIONS(234), 1,
      sym_escape_sequence,
    STATE(54), 1,
      aux_sym_string_repeat1,
  [1160] = 6,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    ACTIONS(102), 1,
      anon_sym_DQUOTE2,
    ACTIONS(236), 1,
      sym_string_content,
    ACTIONS(239), 1,
      sym_escape_sequence,
    STATE(54), 1,
      aux_sym_string_repeat1,
  [1179] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_AT,
    ACTIONS(242), 2,
      anon_sym_namespace,
      anon_sym_instance,
    STATE(55), 2,
      sym_annotation,
      aux_sym_namespace_repeat1,
  [1194] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
    STATE(128), 1,
      sym_record_entry,
    STATE(152), 1,
      sym_string,
  [1213] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1235] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
    STATE(128), 1,
      sym_record_entry,
    STATE(152), 1,
      sym_string,
  [1254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 5,
      ts_builtin_sym_end,
      anon_sym_namespace,
      anon_sym_RBRACE,
      anon_sym_instance,
      anon_sym_AT,
  [1276] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [1306] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    STATE(128), 1,
      sym_record_entry,
    STATE(152), 1,
      sym_string,
  [1322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1332] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [1342] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(269), 3,
      anon_sym_namespace,
      anon_sym_instance,
      anon_sym_AT,
  [1354] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    STATE(100), 1,
      sym_entity_reference,
  [1370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1380] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COLON_COLON,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
    ACTIONS(281), 2,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [1394] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_identifier,
    ACTIONS(288), 1,
      anon_sym_LBRACK,
    STATE(77), 2,
      sym_entity_list,
      sym_entity_reference,
  [1408] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1418] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [1438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [1448] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 4,
      anon_sym_LBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_tags,
  [1458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1478] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
    ACTIONS(304), 1,
      anon_sym_RBRACK,
    STATE(127), 1,
      sym_entity_reference,
  [1491] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    ACTIONS(308), 1,
      anon_sym_COLON_COLON,
    STATE(104), 1,
      aux_sym_entity_reference_repeat1,
  [1504] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_RBRACK,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_entity_list_repeat1,
  [1517] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    ACTIONS(314), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      aux_sym_record_repeat1,
  [1530] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_tags,
    ACTIONS(316), 1,
      anon_sym_SEMI,
    STATE(144), 1,
      sym_instance_tags,
  [1543] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_tags,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    STATE(147), 1,
      sym_instance_tags,
  [1556] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_RBRACK,
    STATE(91), 1,
      aux_sym_set_repeat1,
  [1569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_identifier,
    ACTIONS(324), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_string,
  [1582] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_COLON_COLON,
    ACTIONS(328), 1,
      anon_sym_LPAREN,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
  [1595] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
    ACTIONS(330), 1,
      anon_sym_RBRACK,
    STATE(127), 1,
      sym_entity_reference,
  [1608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      aux_sym_entity_list_repeat1,
  [1621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    ACTIONS(337), 1,
      anon_sym_COMMA,
    STATE(94), 1,
      aux_sym_set_repeat1,
  [1634] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_COMMA,
    ACTIONS(341), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_set_repeat1,
  [1647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1656] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
    ACTIONS(345), 1,
      anon_sym_COMMA,
    STATE(94), 1,
      aux_sym_set_repeat1,
  [1669] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_tags,
    ACTIONS(122), 1,
      anon_sym_SEMI,
    STATE(153), 1,
      sym_instance_tags,
  [1682] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_COMMA,
    ACTIONS(348), 1,
      anon_sym_RPAREN,
    STATE(115), 1,
      aux_sym_set_repeat1,
  [1695] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
    ACTIONS(350), 1,
      anon_sym_COMMA,
    STATE(98), 1,
      aux_sym_record_repeat1,
  [1708] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_RBRACE,
    ACTIONS(354), 1,
      anon_sym_COMMA,
    STATE(98), 1,
      aux_sym_record_repeat1,
  [1721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 3,
      anon_sym_LBRACE,
      anon_sym_COLON_COLON,
      anon_sym_LPAREN,
  [1730] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_COMMA,
    ACTIONS(359), 1,
      anon_sym_RBRACK,
    STATE(82), 1,
      aux_sym_entity_list_repeat1,
  [1743] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_tags,
    ACTIONS(361), 1,
      anon_sym_SEMI,
    STATE(140), 1,
      sym_instance_tags,
  [1756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 3,
      anon_sym_namespace,
      anon_sym_instance,
      anon_sym_AT,
  [1765] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
    ACTIONS(365), 1,
      anon_sym_COLON_COLON,
    STATE(88), 1,
      aux_sym_entity_reference_repeat1,
  [1778] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_COLON_COLON,
    ACTIONS(328), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
  [1791] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_identifier,
    ACTIONS(367), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_string,
  [1804] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_identifier,
    ACTIONS(324), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string,
  [1817] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(322), 1,
      sym_identifier,
    STATE(16), 1,
      sym_string,
  [1830] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(322), 1,
      sym_identifier,
    STATE(18), 1,
      sym_string,
  [1843] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(322), 1,
      sym_identifier,
    STATE(16), 1,
      sym_string,
  [1856] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(322), 1,
      sym_identifier,
    STATE(18), 1,
      sym_string,
  [1869] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(322), 1,
      sym_identifier,
    STATE(16), 1,
      sym_string,
  [1882] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(322), 1,
      sym_identifier,
    STATE(18), 1,
      sym_string,
  [1895] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
    ACTIONS(369), 1,
      anon_sym_COLON_COLON,
    STATE(114), 1,
      aux_sym_entity_reference_repeat1,
  [1908] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_LPAREN,
    ACTIONS(371), 1,
      anon_sym_COLON_COLON,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
  [1921] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_RPAREN,
    ACTIONS(373), 1,
      anon_sym_COMMA,
    STATE(115), 1,
      aux_sym_set_repeat1,
  [1934] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
    ACTIONS(376), 1,
      anon_sym_COLON_COLON,
    STATE(117), 1,
      aux_sym_entity_reference_repeat1,
  [1947] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_LPAREN,
    ACTIONS(378), 1,
      anon_sym_COLON_COLON,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
  [1960] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_identifier,
    ACTIONS(367), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string,
  [1973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1981] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_COLON_COLON,
    STATE(132), 1,
      aux_sym_entity_reference_repeat1,
  [1991] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_identifier,
    STATE(155), 1,
      sym_name,
  [2001] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(84), 1,
      sym_record,
  [2011] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      sym_identifier,
    STATE(23), 1,
      sym_entity_reference,
  [2021] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      sym_identifier,
    STATE(22), 1,
      sym_entity_reference,
  [2031] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      sym_integer,
    ACTIONS(388), 1,
      sym_decimal,
  [2041] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_record,
  [2051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2059] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2067] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      anon_sym_COLON_COLON,
    STATE(134), 1,
      aux_sym_entity_reference_repeat1,
  [2077] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 1,
      anon_sym_COLON_COLON,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
  [2087] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
    STATE(127), 1,
      sym_entity_reference,
  [2097] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_COLON_COLON,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
  [2107] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(150), 1,
      sym_record,
  [2117] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(394), 1,
      anon_sym_COLON_COLON,
    STATE(71), 1,
      aux_sym_entity_reference_repeat1,
  [2127] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_identifier,
    STATE(154), 1,
      sym_name,
  [2137] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(396), 1,
      anon_sym_COLON_COLON,
    STATE(130), 1,
      aux_sym_entity_reference_repeat1,
  [2147] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(101), 1,
      sym_record,
  [2157] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(398), 1,
      anon_sym_DQUOTE,
    STATE(145), 1,
      sym_string,
  [2167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_SEMI,
  [2174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_SEMI,
  [2181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_RBRACK,
  [2188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(400), 1,
      sym_identifier,
  [2195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_identifier,
  [2202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(402), 1,
      anon_sym_SEMI,
  [2209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(404), 1,
      anon_sym_RPAREN,
  [2216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(406), 1,
      ts_builtin_sym_end,
  [2223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_SEMI,
  [2230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(408), 1,
      anon_sym_LPAREN,
  [2237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
  [2244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(410), 1,
      anon_sym_SEMI,
  [2251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_RBRACK,
  [2258] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(412), 1,
      anon_sym_COLON,
  [2265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_SEMI,
  [2272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(414), 1,
      anon_sym_LBRACE,
  [2279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(416), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 89,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 175,
  [SMALL_STATE(7)] = 215,
  [SMALL_STATE(8)] = 255,
  [SMALL_STATE(9)] = 295,
  [SMALL_STATE(10)] = 321,
  [SMALL_STATE(11)] = 337,
  [SMALL_STATE(12)] = 353,
  [SMALL_STATE(13)] = 378,
  [SMALL_STATE(14)] = 401,
  [SMALL_STATE(15)] = 426,
  [SMALL_STATE(16)] = 449,
  [SMALL_STATE(17)] = 464,
  [SMALL_STATE(18)] = 489,
  [SMALL_STATE(19)] = 504,
  [SMALL_STATE(20)] = 529,
  [SMALL_STATE(21)] = 552,
  [SMALL_STATE(22)] = 577,
  [SMALL_STATE(23)] = 605,
  [SMALL_STATE(24)] = 633,
  [SMALL_STATE(25)] = 655,
  [SMALL_STATE(26)] = 677,
  [SMALL_STATE(27)] = 699,
  [SMALL_STATE(28)] = 719,
  [SMALL_STATE(29)] = 739,
  [SMALL_STATE(30)] = 761,
  [SMALL_STATE(31)] = 773,
  [SMALL_STATE(32)] = 785,
  [SMALL_STATE(33)] = 797,
  [SMALL_STATE(34)] = 817,
  [SMALL_STATE(35)] = 837,
  [SMALL_STATE(36)] = 857,
  [SMALL_STATE(37)] = 879,
  [SMALL_STATE(38)] = 899,
  [SMALL_STATE(39)] = 919,
  [SMALL_STATE(40)] = 939,
  [SMALL_STATE(41)] = 959,
  [SMALL_STATE(42)] = 981,
  [SMALL_STATE(43)] = 993,
  [SMALL_STATE(44)] = 1010,
  [SMALL_STATE(45)] = 1021,
  [SMALL_STATE(46)] = 1032,
  [SMALL_STATE(47)] = 1043,
  [SMALL_STATE(48)] = 1054,
  [SMALL_STATE(49)] = 1065,
  [SMALL_STATE(50)] = 1084,
  [SMALL_STATE(51)] = 1103,
  [SMALL_STATE(52)] = 1122,
  [SMALL_STATE(53)] = 1141,
  [SMALL_STATE(54)] = 1160,
  [SMALL_STATE(55)] = 1179,
  [SMALL_STATE(56)] = 1194,
  [SMALL_STATE(57)] = 1213,
  [SMALL_STATE(58)] = 1224,
  [SMALL_STATE(59)] = 1235,
  [SMALL_STATE(60)] = 1254,
  [SMALL_STATE(61)] = 1265,
  [SMALL_STATE(62)] = 1276,
  [SMALL_STATE(63)] = 1286,
  [SMALL_STATE(64)] = 1296,
  [SMALL_STATE(65)] = 1306,
  [SMALL_STATE(66)] = 1322,
  [SMALL_STATE(67)] = 1332,
  [SMALL_STATE(68)] = 1342,
  [SMALL_STATE(69)] = 1354,
  [SMALL_STATE(70)] = 1370,
  [SMALL_STATE(71)] = 1380,
  [SMALL_STATE(72)] = 1394,
  [SMALL_STATE(73)] = 1408,
  [SMALL_STATE(74)] = 1418,
  [SMALL_STATE(75)] = 1428,
  [SMALL_STATE(76)] = 1438,
  [SMALL_STATE(77)] = 1448,
  [SMALL_STATE(78)] = 1458,
  [SMALL_STATE(79)] = 1468,
  [SMALL_STATE(80)] = 1478,
  [SMALL_STATE(81)] = 1491,
  [SMALL_STATE(82)] = 1504,
  [SMALL_STATE(83)] = 1517,
  [SMALL_STATE(84)] = 1530,
  [SMALL_STATE(85)] = 1543,
  [SMALL_STATE(86)] = 1556,
  [SMALL_STATE(87)] = 1569,
  [SMALL_STATE(88)] = 1582,
  [SMALL_STATE(89)] = 1595,
  [SMALL_STATE(90)] = 1608,
  [SMALL_STATE(91)] = 1621,
  [SMALL_STATE(92)] = 1634,
  [SMALL_STATE(93)] = 1647,
  [SMALL_STATE(94)] = 1656,
  [SMALL_STATE(95)] = 1669,
  [SMALL_STATE(96)] = 1682,
  [SMALL_STATE(97)] = 1695,
  [SMALL_STATE(98)] = 1708,
  [SMALL_STATE(99)] = 1721,
  [SMALL_STATE(100)] = 1730,
  [SMALL_STATE(101)] = 1743,
  [SMALL_STATE(102)] = 1756,
  [SMALL_STATE(103)] = 1765,
  [SMALL_STATE(104)] = 1778,
  [SMALL_STATE(105)] = 1791,
  [SMALL_STATE(106)] = 1804,
  [SMALL_STATE(107)] = 1817,
  [SMALL_STATE(108)] = 1830,
  [SMALL_STATE(109)] = 1843,
  [SMALL_STATE(110)] = 1856,
  [SMALL_STATE(111)] = 1869,
  [SMALL_STATE(112)] = 1882,
  [SMALL_STATE(113)] = 1895,
  [SMALL_STATE(114)] = 1908,
  [SMALL_STATE(115)] = 1921,
  [SMALL_STATE(116)] = 1934,
  [SMALL_STATE(117)] = 1947,
  [SMALL_STATE(118)] = 1960,
  [SMALL_STATE(119)] = 1973,
  [SMALL_STATE(120)] = 1981,
  [SMALL_STATE(121)] = 1991,
  [SMALL_STATE(122)] = 2001,
  [SMALL_STATE(123)] = 2011,
  [SMALL_STATE(124)] = 2021,
  [SMALL_STATE(125)] = 2031,
  [SMALL_STATE(126)] = 2041,
  [SMALL_STATE(127)] = 2051,
  [SMALL_STATE(128)] = 2059,
  [SMALL_STATE(129)] = 2067,
  [SMALL_STATE(130)] = 2077,
  [SMALL_STATE(131)] = 2087,
  [SMALL_STATE(132)] = 2097,
  [SMALL_STATE(133)] = 2107,
  [SMALL_STATE(134)] = 2117,
  [SMALL_STATE(135)] = 2127,
  [SMALL_STATE(136)] = 2137,
  [SMALL_STATE(137)] = 2147,
  [SMALL_STATE(138)] = 2157,
  [SMALL_STATE(139)] = 2167,
  [SMALL_STATE(140)] = 2174,
  [SMALL_STATE(141)] = 2181,
  [SMALL_STATE(142)] = 2188,
  [SMALL_STATE(143)] = 2195,
  [SMALL_STATE(144)] = 2202,
  [SMALL_STATE(145)] = 2209,
  [SMALL_STATE(146)] = 2216,
  [SMALL_STATE(147)] = 2223,
  [SMALL_STATE(148)] = 2230,
  [SMALL_STATE(149)] = 2237,
  [SMALL_STATE(150)] = 2244,
  [SMALL_STATE(151)] = 2251,
  [SMALL_STATE(152)] = 2258,
  [SMALL_STATE(153)] = 2265,
  [SMALL_STATE(154)] = 2272,
  [SMALL_STATE(155)] = 2279,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entities, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entities_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entities_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entities_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entities_repeat1, 2, 0, 0), SHIFT_REPEAT(142),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_reference, 4, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_reference, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entities, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 4, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 7, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 8, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 4, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(142),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 5, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 5, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance, 6, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 6, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 5, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__number, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 5, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 4, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 4, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_call, 4, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_reference_repeat1, 2, 0, 0),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entity_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(143),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_call, 5, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 3, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_list, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance_parents, 2, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_call, 3, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 2, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [332] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entity_list_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_list_repeat1, 2, 0, 0),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 0),
  [345] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [354] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 5, 0, 0),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [373] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_entry, 3, 0, 0),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [386] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [406] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [410] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instance_tags, 2, 0, 0),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cedarentities(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cedarentities",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 10,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
